<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/Navbar';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {}
      <body className="antialiased"> 
        
        {}
        <Navbar /> 
        
        {}
        <main className="pt-20"> 
          {children}
        </main>
        
      </body>
    </html>
  );
}